### ISSUE TITLE
SSL certificate error?

### ISSUE THREAD

**Issue by adswa** [ReproNim/repronim.github.io#195] opened 2021-10-01 13:19 UTC
Not sure if this is the right place to complain, but I currently can't go to https://repronim.org:

![Screenshot from 2021-10-01 15-14-16](https://user-images.githubusercontent.com/29738718/135626510-1d3b2f84-f3a9-483a-9744-98445d7fcea4.png)

**Comment by yarikoptic** [comment] 2021-10-01 13:25
attn @chaselgrove

**Comment by satra** [comment] 2021-10-01 13:30
it's the root domain certificate that has expired. if you go to `www.repronim.org` where the certificate is managed by github, it works fine.

**Comment by yarikoptic** [comment] 2021-10-01 13:39
it seems not just expiration issue since even if I decide to proceed, you just get
```
What are you looking for?

Child Portal
Internet Analysis Tools Registry
Internet Brain Volume Database
Image Attribution Framework
```
so redirection doesn't work correctly IMHO.

**Comment by adswa** [comment] 2021-10-01 17:29
I found out because the handbook's monthly linkchecker run failed with 

```
sphinx.errors.SphinxWarning: /home/adina/repos/datalad-handbook/docs/code_from_chapters/yale.rst.rst:219:broken link: https://repronim.org/ (HTTPSConnectionPool(host='repronim.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'repronim.org' doesn't match 'www.virtualbrain.org'"))))
```

([this](http://handbook.datalad.org/en/latest/code_from_chapters/yale.html#dataset-nesting) section contains the link)

**Comment by dnkennedy** [comment] 2021-12-02 17:35
@satra , did your correction yesterday clear this item?

**Comment by satra** [comment] 2021-12-02 17:39
it may have. closing since the original issue cannot be reproduced.

**Closed by satra** 2021-12-02 17:39 UTC
